name: Run Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
        with: 
          node-version: '18.x' 
        - run: npm ci
        - run: npm test
        - run: npm run build
        - run: npm run preview