name: Run Tests

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches: 
    - main 
    - dev

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '18.x' 
      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present
          npm run test
